# Generated by Django 4.2.5 on 2023-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VertrouwdePersonen',
            fields=[
                ('bsn_nummer', models.IntegerField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=128)),
                ('achternaam', models.CharField(max_length=128)),
            ],
        ),
    ]
