# Generated by Django 4.2.5 on 2023-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertrouwdepersonen',
            name='bsn_nummer',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
