# Generated by Django 4.1.7 on 2023-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedusers',
            name='uploaded_file',
            field=models.FileField(default='default_file.txt', upload_to='uploads/'),
        ),
    ]
